---
title: Scott Shapiro’s Blog
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Scott Shapiro
description: Scott Shapiro's personal blog
meta_description: Scott Shapiro's personal blog
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: 
url: https://scottshapiro.com
production_url: https://www.scottshapiro.com/
disqus: 
mailchimp_url: "//scottshapiro.us16.list-manage.com/subscribe/post?u=5c7e9216b6ff26ac8fbd9c161&amp;id=b2ceab4033"
cover_image: bg5.jpg
ga_analytics: UA-92823-1
author:
  name: Scott Shapiro
  image: authorimage.jpg
  greetings: Hi, I'm Scott Shapiro.
  description: I've been working in technology in the Bay Area for the last nine years.
    I've become obsessed with cryptocurrency over the last six. I love pushing myself
    out of my comfort zone, whether technical or physical. This blog serves as a partial
    record of those attempts.
  bio: Scott is a product manager in San Francisco. He has as BS in Computer Science
    from UC San Diego and an MBA from UC Berkeley.
email: youremail@email.com
contact_page_description: Horace theme comes with a contact form built-in. You can
  use this form with Formspree service and get up to 50 submissions for free. Also,
  you can easily switch to another service if you want.
thankyou_page_description: Your message has been successfully sent. We will contact
  you very soon!
twitter: scottshapiro
facebook: scott.shapiro
github: scottshapiro
codepen: 
dribbble: 
medium: 
instagram: scott.shapiro
pinterest: 
linkedin: scottashapiro
producthunt: 
navigation:
- text: About
  url: "/about"
plugins_dir:
- jekyll-paginate
- jekyll-tagsgenerator
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
paginate: 10
paginate_path: "/page:num/"
permalink: "/:title"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
